version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.9
  build:
    commands:
      - aws cloudformation package --template-file sam.yml --s3-bucket yaml-temp --output-template-file outputsam.yml
artifacts:
  files:
    - sam.yml
    - outputsam.yml