version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.9
  build:
    commands:
      - aws cloudformation package --template-file sam.yml --s3-bucket cloud-computing-hw2-lambda --output-template-file outputsam.yml
artifacts:
  files:
    - outputsam.yml