AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  indexphotos:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::884942297675:role/service-role/index-photos-role-y3kcsy98'
      Events:
        BucketEvent1:
          Type: S3
          Properties:
            Bucket:
              Ref: Bucket1
            Events:
              - 's3:ObjectCreated:Put'
      Layers:
        - 'arn:aws:lambda:us-east-1:884942297675:layer:requests_layer:1'
  Bucket1:
    Type: 'AWS::S3::Bucket'
    searchphotos:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::884942297675:role/service-role/search-photos-role-bgvxu30v'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /search
            Method: OPTIONS
        Api2:
          Type: Api
          Properties:
            Path: /search
            Method: GET
      Layers:
        - 'arn:aws:lambda:us-east-1:884942297675:layer:requests_layer:1'
