AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  indexphotos:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::884942297675:role/service-role/index-photos-role-y3kcsy98'
      Environment:
        Variables:
          REGION: us-east-1
  Bucket1:
    Type: 'AWS::S3::Bucket'
    searchphotos:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::884942297675:role/service-role/search-photos-role-bgvxu30v'
      Environment:
        Variables:
          REGION: us-east-1